import "./products"
import "./units"
import "./files/files"
import "./files/server"
import "./brands"
import "./categories"
import "./opening_stock"
import "./place_order"
import "./customer"
// import "./customer/index.js"
import "./order_sell_pos"
// import "./order_sell_pos/method"